name: app_sqlite
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3 

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.5
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^1.2.0
  firebase_core: ^2.32.0
  firebase_database: ^10.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true